function SaveCharacterSheet() {
    var model =
    {
        Nom : $("#input_characterName").val(),
        Niveau : $("input_characterLevel").val(),
        IdClasse : $("listClasses").val(),
        Experience : $("input_characterExperience").val(), 
        IdRace : $("listRaces").val(),  
        CategorieTaille : $("input_characterHeightCategorie").val(), 
        Age : $("input_characterAge").val(), 
        Sexe : $("input_characterSexe").val(), 
        Taille : $("input_characterHeight").val(), 
        Poids : $("input_characterWeight").val(), 
        IdAlignement : $("listAlignements").val(), 
        IdDivinite : $("listDivinites").val(), 
        IdGroupeAventurier : $("input_characterGroup").val(), 
        PointAction : $("input_characterPAValue").val(), 
        PVMax : $("input_character").val(),  
        Personnalite : $("input_character").val(),
        InitiativeDivers : $("input_characterINITDivers").val(),
        CaracteristiqueForce : $("input_ForceValue").val(),
		CaracteristiqueConstitution : $("input_ConsValue").val(),
		CaracteristiqueDexterite : $("input_DexValue").val(),
		CaracteristiqueIntelligence : $("input_IntValue").val(),
		CaracteristiqueSagesse : $("input_SagValue").val(),
		CaracteristiqueCharisme : $("input_ChaValue").val(),
		DefenseCADemiNiveau : $("input_character").val(),
		DefenseCACaracteristique : $("input_character").val(),
		DefenseCAClasse : $("input_character").val(),
		DefenseCATalent : $("input_character").val(),
		DefenseCADivers : $("input_character").val(),
		DefenseVIGDemiNiveau : $("input_character").val(),
		DefenseVIGCaracteristique : $("input_character").val(),
		DefenseVIGClasse : $("input_character").val(),
		DefenseVIGTalent : $("input_character").val(),
		DefenseVIGDivers : $("input_character").val(),
		DefenseREFDemiNiveau : $("input_character").val(),
		DefenseREFCaracteristique : $("input_character").val(),
		DefenseREFClasse : $("input_character").val(),
		DefenseREFTalent : $("input_character").val(),
		DefenseREFDivers : $("input_character").val(),
		DefenseVOLDemiNiveau : $("input_character").val(),
		DefenseVOLCaracteristique : $("input_character").val(),
		DefenseVOLClasse : $("input_character").val(),
		DefenseVOLTalent : $("input_character").val(),
		DefenseVOLDivers: $("input_character").val()
    };
}